//! extern "C" FFI interface — Android JNI bridge + Desktop P/Invoke bridge.
//!
//! Android (Kotlin):
//!   System.loadLibrary("fialka_core")
//!   external fun fialka_generate_identity(seed_ptr: Long, seed_len: Int, out_ptr: Long): Int
//!
//! Desktop (C#):
//!   [DllImport("fialka_core")] static extern int fialka_generate_identity(...)
//!
//! All functions follow the convention:
//!   - Input buffers: *const u8 + len
//!   - Output buffers: *mut u8 + len (caller allocates, function fills)
//!   - Return: 0 = OK, negative = error code
//!
//! Header is auto-generated by cbindgen → fialka_core.h
//!
//! TODO: implement all extern "C" wrappers once crypto modules are complete

// Placeholder — implement in Phase 3
